#!/usr/bin/env python3
"""Download CC0 PNG textures and generate NELA-S texture constants.

This is an offline asset pipeline step:
- downloads texture packs from ambientCG (CC0)
- extracts *_Color.png maps
- downsamples to 16x16
- quantizes pixels to shade ids 6..13
- writes generated NELA-S code block

Runtime game logic remains in NELA-S.
"""

from __future__ import annotations

import io
import pathlib
import urllib.request
import zipfile
from dataclasses import dataclass

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "assets" / "raw"
TEX_DIR = ROOT / "assets" / "textures"
OUT_FILE = ROOT / "examples" / "wolf_textures_generated.nela"

TEX_SIZE = 16


@dataclass(frozen=True)
class TextureSource:
    name: str
    url: str


SOURCES = [
    TextureSource("brick", "https://ambientcg.com/get?file=Bricks056_1K-PNG.zip"),
    TextureSource("planks", "https://ambientcg.com/get?file=Planks017_1K-PNG.zip"),
    TextureSource("metal", "https://ambientcg.com/get?file=MetalPlates006_1K-PNG.zip"),
]


def download_zip(src: TextureSource) -> pathlib.Path:
    out = RAW_DIR / f"{src.name}.zip"
    if out.exists():
        return out
    print(f"Downloading {src.name}...")
    req = urllib.request.Request(
        src.url,
        headers={
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
            "Accept": "application/zip,*/*",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    out.write_bytes(data)
    return out


def extract_color_png(zip_path: pathlib.Path, name: str) -> pathlib.Path:
    out_png = TEX_DIR / f"{name}.png"
    if out_png.exists():
        return out_png

    with zipfile.ZipFile(zip_path) as zf:
        candidates = [
            zi.filename
            for zi in zf.infolist()
            if zi.filename.lower().endswith("_color.png")
        ]
        if not candidates:
            raise RuntimeError(f"No *_Color.png found in {zip_path}")
        chosen = sorted(candidates)[0]
        img_data = zf.read(chosen)

    # Keep a compact preview PNG in-repo instead of full 1K source texture.
    img = Image.open(io.BytesIO(img_data)).convert("RGB").resize((TEX_SIZE, TEX_SIZE), Image.Resampling.BILINEAR)
    img.save(out_png)
    return out_png


def png_to_shade_rows(png_path: pathlib.Path) -> list[list[int]]:
    img = Image.open(png_path).convert("RGB").resize((TEX_SIZE, TEX_SIZE), Image.Resampling.BILINEAR)
    rows: list[list[int]] = []
    for y in range(TEX_SIZE):
        row: list[int] = []
        for x in range(TEX_SIZE):
            r, g, b = img.getpixel((x, y))
            lum = int(0.299 * r + 0.587 * g + 0.114 * b)
            band = max(0, min(7, lum // 32))
            row.append(6 + band)  # texture shades occupy 6..13
        rows.append(row)
    return rows


def nela_list(rows: list[list[int]]) -> str:
    lines = ["["]
    for i, row in enumerate(rows):
        suffix = "," if i < len(rows) - 1 else ""
        lines.append("  [" + ", ".join(str(v) for v in row) + "]" + suffix)
    lines.append("]")
    return "\n".join(lines)


def build_nela_block(textures: dict[str, list[list[int]]]) -> str:
    names = list(textures.keys())
    out: list[str] = []
    out.append("-- AUTO-GENERATED by tools/build_wolf_textures.py")
    out.append("-- Source textures: ambientCG CC0")
    out.append(f"def tex_size = {TEX_SIZE}")
    out.append("")

    for i, name in enumerate(names):
        out.append(f"def tex_{name} =")
        out.append(nela_list(textures[name]))
        out.append("")

    # deterministic selector for wall columns
    out.append("def wall_tex_id col =")
    out.append(f"  (col / 13) mod {max(1, len(names))}")
    out.append("")

    if len(names) == 1:
        out.append(f"def tex_pick tex_id = tex_{names[0]}")
    else:
        out.append("def tex_pick tex_id =")
        first = True
        for i, name in enumerate(names):
            if i == 0:
                out.append(f"  if tex_id == {i} then tex_{name}")
            elif i < len(names) - 1:
                out.append(f"  else if tex_id == {i} then tex_{name}")
            else:
                out.append(f"  else tex_{name}")
    out.append("")

    out.append("def tex_sample tex_id u v =")
    out.append("  let tex = tex_pick tex_id in")
    out.append(f"  let row = get tex (v mod {TEX_SIZE}) in")
    out.append(f"  get row (u mod {TEX_SIZE})")
    out.append("")

    return "\n".join(out)


def main() -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    TEX_DIR.mkdir(parents=True, exist_ok=True)

    textures: dict[str, list[list[int]]] = {}
    for src in SOURCES:
        z = download_zip(src)
        p = extract_color_png(z, src.name)
        textures[src.name] = png_to_shade_rows(p)
        try:
            z.unlink()
        except OSError:
            pass

    block = build_nela_block(textures)
    OUT_FILE.write_text(block + "\n", encoding="utf-8")
    print(f"Generated {OUT_FILE}")


if __name__ == "__main__":
    main()
